name: Run Larastan

on:
  # Triggers the workflow on pull request events
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run_larastan:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Setup PHP
          uses: shivammathur/setup-php@2.18.0
          with:
           php-version: 8.2

        - name: Install dependencies
          run: |
            composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
            composer update --prefer-stable --prefer-dist --no-interaction

        - name: Larastan
          run: ./vendor/bin/phpstan analyse --no-progress

        - name: Upload artifacts
          uses: actions/upload-artifact@v3
          if: failure()
          with:
            name: Logs
            path: ./storage/logs
