name: Run Pest PHP

on:
  # Triggers the workflow on pull request events
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run_pest_test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: testing_new_pxm
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@2.18.0
      with:
        php-version: 8.2

    - name: Install dependencies
      run: |
        composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        composer update --prefer-stable --prefer-dist --no-interaction

    - name: Prepare laravel application
      run: |
        cp .env.example .env
        php artisan key:generate

    - name: Tests
      run: ./vendor/bin/pest

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: Logs
        path: ./storage/logs
