name: Run Laravel Pint

on:
  # Triggers the workflow on pull request events
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run_pint:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
        - name: Checkout code
          uses: actions/checkout@v3
          with:
            ref: ${{ github.event.pull_request.head.sha }}

        - name: Setup PHP
          uses: shivammathur/setup-php@2.18.0
          with:
           php-version: 8.2

        - name: Install dependencies
          run: |
            composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
            composer update --prefer-stable --prefer-dist --no-interaction

        - name: Pint
          run: ./vendor/bin/pint

        - name: Fetch latest changes from main
          run: git fetch origin main

        - name: Fetch latest changes from current branch
          run: git fetch origin ${{ github.event.pull_request.head.ref }}

        - name: Check if working directory is dirty
          id: check_dirty
          run: |
            dirty=$(git status --porcelain)
            echo "::set-output name=is_dirty::$(if [ -n "$dirty" ]; then echo "true"; else echo "false"; fi)"

        - name: Prepare git user
          run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "action@github.com"

        - name: Commit and push changes
          if: steps.check_dirty.outputs.is_dirty == 'true'
          run: |
            git add .
            git commit -m "code: refactor by pint"
            git push origin ${{ github.event.pull_request.head.ref }}
