name: Check & fix styling

on:
    schedule: # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onschedule
        - cron: "0 0 * * 0" # This cron expression triggers the workflow at midnight (UTC) every Sunday
jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - name: Fix styling issues
        uses: aglipanci/laravel-pint-action@0.1.0

      - name: Run Rector
        run: |
            composer global require "rector/rector:^0.15.24" "driftingly/rector-laravel:^0.17.0" --no-interaction --no-update
            composer update --prefer-stable --prefer-dist --no-interaction
            ./vendor/bin/rector process --clear-cache

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_email: action@github.com
          commit_message: Fix styling
